---

- job:
    name: unit-tests
    parent: base
    description: this is running the unit tests for this project
    pre-run: playbooks/pre-setup.yaml
    run: playbooks/unittests.yaml
    post-run: playbooks/fetch-logs.yaml
    required-projects:
        - demo-1
    voting: false
    nodeset:
      nodes:
# pool's name, not nodes node, it's `nodes`
        - name: main 
          label: dlrn-worker 

- project:
    name: demo-project
    check:
      jobs:
        - tox-py27
        - demo-rpmbuild
        - unit-tests
    gate:
      jobs:
        - tox-py27
        - unit-tests
